<?php

namespace App\Filament\Resources;

use App\Models\Report;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Infolists;
use Filament\Infolists\Infolist;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Actions\ViewAction;

class ReportResource extends Resource
{
    protected static ?string $model = Report::class;

    protected static ?string $navigationIcon = 'heroicon-o-chart-bar';

    protected static ?string $navigationGroup = 'Management';

    protected static ?string $navigationLabel = 'Reports';

    protected static ?string $modelLabel = 'Report';

    public static function getNavigationLabel(): string
    {
        return __('Reports');
    }

    public static function getNavigationGroup(): ?string
    {
        return __('Reports');
    }

    public static function getPluralModelLabel(): string
    {
        return __('Reports');
    }

    public static function getModelLabel(): string
    {
        return __('Report');
    }

    public static function getPages(): array
    {
        return [
            'index' => \App\Filament\Resources\ReportResource\Pages\ListReports::route('/'),
            'view' => \App\Filament\Resources\ReportResource\Pages\ViewReport::route('/{record}'),
        ];
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make(__('Report Info'))
                    ->schema([
                        Forms\Components\TextInput::make('title')
                            ->label(__('Title'))
                            ->required()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('type')
                            ->label(__('Type'))
                            ->required()
                            ->maxLength(255),
                        Forms\Components\Select::make('generated_by')
                            ->label(__('Generated By'))
                            ->relationship('user', 'name')
                            ->searchable()
                            ->preload(),
                        Forms\Components\DateTimePicker::make('generated_at')
                            ->label(__('Generated At')),
                    ])
                    ->columns(2),
                Forms\Components\Section::make(__('Data'))
                    ->schema([
                        Forms\Components\KeyValue::make('data')
                            ->label(__('Data'))
                            ->keyLabel(__('Key'))
                            ->valueLabel(__('Value'))
                            ->reorderable()
                            ->columnSpanFull(),
                    ]),
            ]);
    }

    public static function infolist(Infolist $infolist): Infolist
    {
        return $infolist
            ->schema([
                Infolists\Components\Section::make(__('Report Info'))
                    ->schema([
                        Infolists\Components\TextEntry::make('title')
                            ->label(__('Title'))
                            ->weight('bold'),
                        Infolists\Components\TextEntry::make('type')
                            ->label(__('Type'))
                            ->badge()
                            ->color(fn (string $state): string => match ($state) {
                                'summary' => 'info',
                                'detailed' => 'warning',
                                'analytics' => 'success',
                                default => 'gray',
                            }),
                        Infolists\Components\TextEntry::make('user.name')
                            ->label(__('Generated By')),
                        Infolists\Components\TextEntry::make('generated_at')
                            ->label(__('Generated At'))
                            ->dateTime(),
                    ])
                    ->columns(2),
                Infolists\Components\Section::make(__('Data'))
                    ->schema([
                        Infolists\Components\KeyValueEntry::make('data')
                            ->label('')
                            ->keyLabel(__('Key'))
                            ->valueLabel(__('Value')),
                    ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('title')
                    ->label(__('Title'))
                    ->searchable()
                    ->sortable(),
                TextColumn::make('type')
                    ->label(__('Type'))
                    ->searchable(),
                TextColumn::make('generated_at')
                    ->label(__('Generated At'))
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('user.name')
                    ->label(__('Generated By')),
            ])
            ->filters([
                SelectFilter::make('type')
                    ->label(__('Type'))
                    ->options([
                        'summary' => 'Summary',
                        'detailed' => 'Detailed',
                        'analytics' => 'Analytics',
                    ]),
                Filter::make('generated_at')
                    ->label(__('Generated This Month'))
                    ->query(fn ($query) => $query->whereMonth('generated_at', now()->month)),
            ])
            ->actions([
                ViewAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [];
    }
}
