<?php

namespace App\Filament\Resources;

use App\Models\Report;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Actions\ViewAction;

class ReportResource extends Resource
{
    protected static ?string $model = Report::class;

    protected static ?string $navigationIcon = 'heroicon-o-chart-bar';

    protected static ?string $navigationGroup = 'Management';

    protected static ?string $navigationLabel = 'Reports';

    protected static ?string $modelLabel = 'Report';

    public static function getPages(): array
    {
        return [
            'index' => \App\Filament\Resources\ReportResource\Pages\ListReports::route('/'),
            'view' => \App\Filament\Resources\ReportResource\Pages\ViewReport::route('/{record}'),
        ];
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Report Info')
                    ->schema([
                        Forms\Components\TextInput::make('title')
                            ->label('Title')
                            ->required()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('type')
                            ->label('Type')
                            ->required()
                            ->maxLength(255),
                        Forms\Components\Select::make('generated_by')
                            ->label('Generated By')
                            ->relationship('user', 'name')
                            ->searchable()
                            ->preload(),
                        Forms\Components\DateTimePicker::make('generated_at')
                            ->label('Generated At'),
                    ])
                    ->columns(2),
                Forms\Components\Section::make('Data')
                    ->schema([
                        Forms\Components\MarkdownEditor::make('data')
                            ->label('Data')
                            ->columnSpanFull(),
                    ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('title')
                    ->label('Title')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('type')
                    ->label('Type')
                    ->searchable(),
                TextColumn::make('generated_at')
                    ->label('Generated At')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('generated_by')
                    ->label('Generated By'),
            ])
            ->filters([
                SelectFilter::make('type')
                    ->label('Type')
                    ->options([
                        'summary' => 'Summary',
                        'detailed' => 'Detailed',
                        'analytics' => 'Analytics',
                    ]),
                Filter::make('generated_at')
                    ->label('Generated This Month')
                    ->query(fn ($query) => $query->whereMonth('generated_at', now()->month)),
            ])
            ->actions([
                ViewAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [];
    }
}
